version: '3.8'
services:
  # app service for your backend
  nest:
    container_name: 'nest'
    build:
      context: .
      target: development
      # dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    # environment:
    #   DATABASE_NAME: ${MONGO_DATABASE}
    #   DATABASE_USER: ${MONGO_USERNAME}
    #   DATABASE_PASS: ${MONGO_PASSWORD}
    #   DATABASE_URI: ${DATABASE_URI}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: 'mymongodb'
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    env_file:
      - .env
    environment:
      # - MONGO_INITDB_DATABASE=${MONGO_DATEBASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data_container:/data/db

networks:
  webnet:
volumes:
  mongodb_data_container:
